### ISSUE TITLE
Feature Request: Audio Output configurability

### ISSUE THREAD

**Issue by subwuy** [pvrs12/Anesidora#10]
Requesting a way to change the default output for audio. 

I run this to manage my audio in chrome

https://chrome.google.com/webstore/detail/audiopick/gfhcppdamigjkficnjnhmnljljhagaha?utm_source=chrome-app-launcher-info-dialog

but it doesn't seem to affect this addon.

**Comment by pvrs12** [comment]
Hmm, not sure why this is an issue. All the extension does is create a background window with an `<audio>` tag. I'm surprised that this doesn't conform to the audio output that your other extension sets up. 

I'll see if I can test this further. Unfortunately I've done most of my dev work on Firefox, so I'll have to get used to the differences (hopefully not many) in chrome

**Comment by subwuy** [comment]
thanks for looking at it.


________________________________
