### ISSUE TITLE
Stopped working on Firefox.

### ISSUE THREAD

**Issue by lovelydumpling** [pvrs12/Anesidora#107]
Hi! I use the Firefox version and have enjoyed it for years (Thank you so much btw)
But as of tonight it seems to have stopped working. If I pull up Brave which I used to use, it still works there, so the Chrome version seems fine. But the Firefox version suddenly isn't playing any songs. If I click play, or skip song, or choose a station, nothing happens and no songs play. 

EDIT: Saw a suggestion in another post to check the debug console, when I try to play music or pick a playlist I get
"Uncaught (in promise) TypeError: currentPlaylist is undefined"
![image](https://github.com/pvrs12/Anesidora/assets/30986053/dcf145c7-12c8-437f-8e1a-0e4ddf7b1e98)

**Comment by lovelydumpling** [comment]
Nevermind...? It wasn't working again tonight but then it suddenly did after I spam clicked the play button. I... sure. Okay. Cool.

**Comment by hucario** [comment]
Sorry I wasn't here to help in time - currently I have limited internet access. I'm glad things worked out for you.
