### ISSUE TITLE
Resuming play after sleep

### ISSUE THREAD

**Issue by thesamim** [pvrs12/Anesidora#11]
This is very minor....

Firefox 58.0b14 (64-bit) on Windows 10.

1. Machine goes to sleep.
2. Come back, wake it up, login.
3. Finish playing current song. Song plays fine.
4. Next song won't play.
5. Clicking Play on the player won't restart it.
6. Going to the Station selector and selecting the station again gets everything back in working other.

Happened to have Fidler open one time: the request for the next song and the click on Play result in HTTP 403 return codes. Would be cool if Anesidora would catch those and redo the authentication on the fly... :)

Thanks for a fantastic extension. 👍

**Comment by pvrs12** [comment]
This should be fixed in this PR. I'm going to try to cover a few more issues and then make another release on the webstore
