### ISSUE TITLE
Feture Request: Download as mp3

### ISSUE THREAD

**Issue by sclient** [pvrs12/Anesidora#15]
Confused as to why it only has an .mp4 option.. Love the addon, btw! All my other pandora stuff is completely broken by their ad detection, but this one works perfectly.
Edit: Come to think of it, Im using this on firefox, but I may actually be using the chrome version, and that may be the cause. Ill have to see if there is a quantum compatible version.

No luck.

**Comment by pvrs12** [comment]
The `.mp4` files are what is provided by Pandora. There may be other audio sources that download as `.mp3`, but they will be of lower quality
