### ISSUE TITLE
Feature request: Remove thumbs up w/o thumbs down or I dont want to hear this song.

### ISSUE THREAD

**Issue by sclient** [pvrs12/Anesidora#16]
Sometimes I like to not totally TD a certain artist or song, so that it will still play sometimes.

**Comment by pvrs12** [comment]
You can try the "snooze" button (https://raw.githubusercontent.com/pvrs12/Anesidora/master/common/images/sleep.png) which will put the song on hold for a bit. 

I can't add any other features as I'm limited by the Pandora API to these 3 options
