### ISSUE TITLE
Left button panel broken on FF Quantum.

### ISSUE THREAD

**Issue by sclient** [pvrs12/Anesidora#17]
Funny cause it works if I use the chrome version. The area where you can set the thumbs/down on previous songs just doesnt appear to show up. I will test is a browser restart changes this and report later.

**Comment by sclient** [comment]
Yup, its still broken upon reboot. Reinstalling chrome version for now.

**Comment by pvrs12** [comment]
Hey, sorry this was left sitting for a while. Have you tested if this issue still occurs recently? I haven't had this problem before
