### ISSUE TITLE
UI not rendering correctly?

### ISSUE THREAD

**Issue by mnelson10000** [pvrs12/Anesidora#2]
It may have begun with a Firefox update, but recently Anesidora's UI isn't rendering correctly.  All of the buttons are stacked vertically and I have to arrow down to see all of them (see the attached screenshots). Ideas?  Thanks 
![screen shot 07-16-17 at 12 24 pm 001](https://user-images.githubusercontent.com/16744059/28249331-d2484c10-6a21-11e7-9a4c-ae210a0a29cc.PNG)
![screen shot 07-16-17 at 12 24 pm](https://user-images.githubusercontent.com/16744059/28249330-d246057c-6a21-11e7-90cf-9a6138c4913e.PNG)

**Comment by pvrs12** [comment]
Yikes that is ugly. Can you send me your Troubleshooting Information so I can try to replicate it?

Should be able to do that via `Help > Troubleshooting Information> Copy Text to Clipboard` and then post it here

**Comment by mnelson10000** [comment]
Actually, Firefox updated just after I sent that and it's fine now!  Weird, it's been going on for weeks.  Thanks anyway!  Love the add-on, nice work.  👍
