### ISSUE TITLE
Addon not logging in with Firefox

### ISSUE THREAD

**Issue by aaron766** [pvrs12/Anesidora#20]
I'm unable to log into Anesidora using the addon in Mozilla Firefox. I was having the same issue with Chrome, but was still able to use Firefox until the latest update. I know I am using the correct information to log in, but nothing happens once I input my username and password.

**Comment by pvrs12** [comment]
This is probably related to #18.

Go to https://tuner.pandora.com. I suspect you will have a certificate
error. You should be able to add a permanent exception from there, which I
think will fix your error

**Comment by aaron766** [comment]
When I try to go to the link I get "403 Forbidden. You don't have permission to access / on this server."

**Comment by pvrs12** [comment]
Yes, that's expected, did it have a "green lock" in the top left at the
address bar?

**Comment by aaron766** [comment]
It did, yes.

**Comment by tydonk** [comment]
That fixed it for me.  @aaron766 try logging in again after adding the exception

**Comment by aaron766** [comment]
Still unsure what to do right after I go the link and get the forbidden page. I don't see anything about adding an exception.

**Comment by Blarrgh** [comment]
Same.  Wasn't working, added a permanent exception, still doesn't work.  Looks like it's trying to, but no music.

**Comment by sclient** [comment]
In having the same issue on Opera. Need update! Somehow I also have a newer version than the github release, which is spooky AF? 1.11.1?
