### ISSUE TITLE
Can not import https://tuner.pandora.com cert in latest chrome build

### ISSUE THREAD

**Issue by khezekiah** [pvrs12/Anesidora#21]
Any new work around? 
https://www.wordfence.com/blog/2018/03/chrome-symantec-distrust-certificates-ssl-tls/

**Comment by thesamim** [comment]
Have you tried going to https://tuner.pandora.com/ directly, accepting the security exception and trying again?

This works in firefox.

**Comment by pvrs12** [comment]
You should still be able to trust the cert. Try going there and clicking "Advanced" then "Proceed to tuner.pandora.com (unsafe)"

I've also put instructions in https://github.com/pvrs12/Anesidora/blob/master/certificate.md

**Comment by khezekiah** [comment]
Ahh yes, clicking Proceed to... fixes the issue, thank you

**Comment by pvrs12** [comment]
Glad that worked for you. I added a popup to Anesidora whenever someone has an incorrect login to direct them to those instructions. Hopefully that will help people. 

I still have to update the Chrome version though
