### ISSUE TITLE
Broken Login

### ISSUE THREAD

**Issue by Zalext** [pvrs12/Anesidora#23]
Hi,

As said in the Chrome Store reviews, the Login is broken.
Will this be addressed?

Thank you.

**Comment by pvrs12** [comment]
Hi, I know about the login issues, however it is unfortunately not something that I can fix. It is due to an distrusted HTTPS certificate at https://tuner.pandora.com.

I have instructions for working around the issue at https://github.com/pvrs12/Anesidora/blob/master/certificate.md

**Comment by pvrs12** [comment]
see also #20

**Comment by Zalext** [comment]
Thank you!
It's fixed! :D

I've read on the store about a fix but didn't found it,
I thought that all the files on the "Code" site were files inside the extension itself.

--

Maybe,
Would be useful an "issue" titled:

- "**FIX - Broken login**" 

and point to the fix site?

--
--

Thanks again!
