### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by karlshall2000** [pvrs12/Anesidora#26]
Latest chrome OS version you can't log in. stopped working after update. Hope you can fix it. Thanks

**Comment by karlshall2000** [comment]
Chrome OS version 67.03396.99 official build 32 bit

**Comment by pvrs12** [comment]
Hi, look at this document. I suspect you're having a certificate error, this document gives some details and should help you workaround

https://github.com/pvrs12/Anesidora/blob/master/certificate.md

**Comment by karlshall2000** [comment]
Hi, thanks for replying back to me so quickly. I'm sure that the information you have given me would work, unfortunately, the administraor of my computer has that link blocked. Thanks again

**Comment by pvrs12** [comment]
Does it say "Forbidden" if so that's probably from Pandora.

If it is definitely from your administrator then unfortunately Anesidora
won't work for you, it requires access to that URL.

**Comment by karlshall2000** [comment]
I cant get to the forbidden screen. I could access anesidora fine before I did the chrome update. Thanks for your help though.

**Comment by pvrs12** [comment]
Hmmm. Idk if you can install Firefox, but you could give that a try. I can
look tomorrow to see if there is some way to add an exception to chrome
without visiting that site.
