### ISSUE TITLE
Support for Android Firefox

### ISSUE THREAD

**Issue by seveerekaj** [pvrs12/Anesidora#3]
I went to the add-on store for Firefox on my Android phone, and Anesidora was listed in the options. I use the desktop version every day so I figured it would be awesome to have the same thing on my phone. I installed it, and Firefox told me that it installed properly, but I could not access it. Selecting the add-on from the toolbar menu did nothing. Would it be possible to create a working version for Android Firefox? That would be the best thing ever....

**Comment by pvrs12** [comment]
I agree! It's my next on the list. I have to figure out what the differences are between normal Firefox and Android Firefox. My plan is likely to take the popup page and turn it into a separate tab for the Android version. I hope this is a simple change, but I've got no clue. I'll update this ticket if (when) I make these updates

**Comment by pvrs12** [comment]
I've got some very basic android support implemented! The version on the mozilla store should be up-to-date and you should be able to install it on Firefox for Android whenever you want.

Fair warning, it is pretty ugly on Android right now, but it does work. Hope it works for you!

**Comment by seveerekaj** [comment]
Thanks for working on this! I downloaded the latest version (1.10.0) but it still does not work. I tried loading it from the menu on Android Firefox. "Anesidora" shows up in the menu but selecting it does nothing. Is there some other way I should be executing it?

**Comment by pvrs12** [comment]
Hmm, what version of firefox for Android do you have installed? I've been testing on 56.0

**Comment by seveerekaj** [comment]
Firefox 56.0
Android version 7.0
Moto G5 Plus

**Comment by seveerekaj** [comment]
I tried uninstalling Firefox and then reinstalling it, and now it works!

**Comment by pvrs12** [comment]
Well crap. That's nearly the same as mine (just LG G6 instead)...

**Comment by pvrs12** [comment]
Oh sweet, just as I read the specs! Glad it's working!
