### ISSUE TITLE
Feature Request: Enforce HTTPS

### ISSUE THREAD

**Issue by JHahnHRO** [pvrs12/Anesidora#31]
As I understand the insane restriction to US users is not active when all connections to Pandora to through HTTPS (as witnessed by the webplayer). Would you please change the extension so that us citizens of the rest of the world can enjoy it without using VPNs?

**Comment by pvrs12** [comment]
Good call, I'll add this. Probably going to do so as an Option rather than something fully enforced due to this https://github.com/pvrs12/Anesidora/blob/master/certificate.md

**Comment by pvrs12** [comment]
This should now be fixed in the most recent version.
