### ISSUE TITLE
Feature Request: sort station list

### ISSUE THREAD

**Issue by GT-GH** [pvrs12/Anesidora#34]
Please add a way of sorting the station list, or at least make some kind of sorting (alphabetical?) the default. Right now, the stations seem to be listed in random order and can be difficult to find. Thanks!

**Comment by pvrs12** [comment]
I agree, this is a pain. I'll look into this and see what I can do. I'd also like to add a search bar at the top to filter them.

**Comment by pvrs12** [comment]
I've added sorting alphabetically (currently the only option) and a filter box which will help when there is a lot of stations.

**Comment by GT-GH** [comment]
Perfect! Thank you very much!
