### ISSUE TITLE
Songs That are Thumbed Up Do Not Show Up In History

### ISSUE THREAD

**Issue by nZiemba** [pvrs12/Anesidora#35]
I'm not sure if this is intentional, but songs that I have "thumbed up" do not appear in the history section, and I can't find anything in the options to change this.

**Comment by pvrs12** [comment]
That was an oversight, I'll look into adding it

**Comment by JohnLikesComputers** [comment]
Just to quickly chime in, I'm having the same issue. If anyone needs any logs to help diagnose let me know. 
Firefox Version.

**Comment by pvrs12** [comment]
I _think_ this is fixed in the redesign. If not let me know and I'll re-open the issue

**Comment by nateworld323** [comment]
It is fixed, tremendous. And it looks great with the redesign! Thank you.

**Comment by pvrs12** [comment]
All thanks to @hucario!
