### ISSUE TITLE
PhraseExpress Triggers Play / Pause in Firefox

### ISSUE THREAD

**Issue by professorrc** [pvrs12/Anesidora#36]
Using PhraseExpress (14.0.145f) on Windows 10 (1903) with Firefox 67.0.3
Whenever I trigger a phrase to expand in Firefox it toggles the play / pause in Anesidora.
When outside of firefox (with firefox still open), it doesn't tigger Anesidora's play / pause.
It happens when typing on websites, in the address bar, and in the search bar.

I have not tested in other browsers

**Comment by pvrs12** [comment]
I'm not sure what causes this exactly, but I suspect it's related to https://bugzilla.mozilla.org/show_bug.cgi?id=1251795

I have the same issue when I use auto-hotkey to replace phases. 

I'll to some testing to verify that it's related to that bug. If it is, then a quick fix for it would be to rebind the Play/Pause key to a non-media key (like alt+p)

edit:
.... i just realized i told you to rebind the Play/Pause key, but didn't provide the ability to do so

**Comment by pvrs12** [comment]
Ok, I've confirmed that it is related to the Play/Pause key being bound. 

I'm going to be adding configurability for the hotkeys. That should help to alleviate this issue.

**Comment by pvrs12** [comment]
I've added hotkey configuration, which should at least provide a workaround. I'm assuming this is tied to the FF bug, so until that is fixed, I probably can't fix this bug.
