### ISSUE TITLE
A number of seeming random keystrokes, especially the extra keys on the top of the MS Wave keyboard (play/pause, any of the assigned number keys) start the player. 

### ISSUE THREAD

**Issue by mark-eh** [pvrs12/Anesidora#37]
A number of seeming random keystrokes, especially the extra keys on the top of the MS Wave keyboard (play/pause, any of the assigned number keys) start the player.

**Comment by professorrc** [comment]
I wonder if this issue is related to this one: https://github.com/pvrs12/Anesidora/issues/36

**Comment by pvrs12** [comment]
I believe this is as a result of this Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1251795. 

I unfortunately can't help it. This is why the only media key that is bound is Play/Pause and Next Song is Alt+N rather than the skip button.
