### ISSUE TITLE
No sound.

### ISSUE THREAD

**Issue by DarkAlchy** [pvrs12/Anesidora#48]
I just installed this in FF and there is no sound but in Chrome I have sound from it.  Any idea what I need to check on my end for this as I suspect it could be on my side.  I use noscript, privacybadger, and ublock origins.

**Comment by pvrs12** [comment]
No clue tbh. Fundamentally it is just opening an "invisible" background page and loading a `.mp3` on it and playing. If that works for other pages it should work fine for Anesidora. As you've mentioned it's probably on your side. You can probably fix it by whitelisting the extension's endpoint. If you click on the "options button" (a gear) you should see the URL is something like `moz-extension`. You can probably whitelist that in all of your privacy extensions to see if it clears up the issue

**Comment by DarkAlchy** [comment]
How I fixed it (been almost 6 months since this was ticketed with not a single response so I clean forgot about it) was I upgraded my FF and it worked.
