### ISSUE TITLE
Continuously Logging Out

### ISSUE THREAD

**Issue by JathTyki** [pvrs12/Anesidora#49]
Hello,

I am noticing within the past day or so that Anesidora is continuously getting logged out. What happens is when listening to music, music will still play but you can't use any functions. If you try to skip, like, dislike, or change a radio station, it won't do anything. Like you weren't even clicking on the buttons. You need to close out of the browser and reopen.

When you reopen the browser, at that point you will be prompted to login to Anesidora again. However, credentials will not work. Even though those same credentials work on Pandora.com perfectly fine, Anesidora will not accept the credentials.

So far I noticed that after waiting a bit Anesidora will allow you to enter credentials again, but right at this exact moment it isn't allowing them even after waiting for over 10-15 minutes.

Uninstall and reinstall of the app does not help with this issue.

![image](https://user-images.githubusercontent.com/8599699/73372950-02e78680-4286-11ea-86f5-b85e9960969f.png)

**Comment by pvrs12** [comment]
It seems like your creds may be getting invalidated. I've never really ran into this issue except when messing with the API for new features (and as a result doing things that the pandora backend finds "suspicious").

If you can grab network logs I _may_ be able to track something down, but if you send those to me (via some private channel) I would get your pandora password. I'd rather avoid this...

As one other effort you could check the browser logs (`Ctrl + Shift + J`) to see if there is anything crazy going on in them.
