### ISSUE TITLE
player icons are uneven

### ISSUE THREAD

**Issue by hucario** [pvrs12/Anesidora#57]
oh hey it's me again
the player icons are slightly wonky and/or inconsistent because I didn't really review the icons that well
![image](https://user-images.githubusercontent.com/50851047/88444421-40af0d00-cdda-11ea-8adb-f8b6d3676f64.png)

**Comment by pvrs12** [comment]
Totally missed responding to this. It's something that I might poke into in the future (or if you do ¯\_(ツ)_/¯).

In general I'm probably putting dev on this on hold for a bit

**Comment by hucario** [comment]
guess it's just a firefox extension now ¯\\_(ツ)_/¯

**Comment by pvrs12** [comment]
Rip in peas

________________________________
