### ISSUE TITLE
not available on chrome webstore

### ISSUE THREAD

**Issue by drnick88101** [pvrs12/Anesidora#61]
Sorry if this is the wrong place to post this, i didnt know where else to get ahold of anyone. The addon page on the chrome webstore dosent exist anymore.  As a workaround i manually downloaded the addon, enabled developer mode, and installed that way but i get a message to disable it everytime the browser starts so id prefer it if you can add it back to chrome addon page.

**Comment by pvrs12** [comment]
Hi, you're right. I actually received a copyright infringement notice from Pandora requesting that I take it down.

I suspect that with some changes and a legal battle it may be able to be re-published, however this isn't something that I am willing to do.

**Comment by pvrs12** [comment]
If you'd like you can re-publish the extension there

**Comment by drnick88101** [comment]
Republish it where?
