### ISSUE TITLE
Download link on page for Chrome is 404.

### ISSUE THREAD

**Issue by DarkAlchy** [pvrs12/Anesidora#66]
As the title says the page is simply not there as I am trying to migrate away from Mozilla after 16 years to Brave (A Chromium privacy centric browser).

**Comment by pvrs12** [comment]
I received a DMCA takedown request from Pandora for the extension on Chrome. It is not worth a legal fight for me to attempt to ignore it. I'll update the readme to remove the Chrome link.

You can still download the extension and load it manually via browsing to `chrome://extensions`

**Comment by DarkAlchy** [comment]
I do not know where to get the chrome one to do that?  I am not opposed to side loading (so to speak) on the PC as I am forced to do on my smartphone.

**Comment by pvrs12** [comment]
https://github.com/pvrs12/Anesidora/releases/tag/v2.0.0
`anesidora_chrome.zip`

**Comment by DarkAlchy** [comment]
Thank you.

Yeah, Google is like Apple 2.0 and both sleep in the same bed (literally) as big tech needs to perish as they do, 100%, collude with each other.
