### ISSUE TITLE
Control Panel Cropped - Display stations and volume control doesn't show

### ISSUE THREAD

**Issue by jngapp** [pvrs12/Anesidora#7]
![firefox_anesidora_bug](https://user-images.githubusercontent.com/31453488/33011186-47475692-cd81-11e7-8fe0-a8b94d2c9f81.png)
56.0.1 (64-bit)
I'm not sure if you're already aware of this issue, but as you see in the screenshot, the control screen got cropped, I can't change channel or volume on my browser anymore.

**Comment by pvrs12** [comment]
Huh, that's interesting... Did you change the width from the options menu to shrink it down that small?

As far as a fix for you right now, you should be able to click the rightmost button (which is partially cutoff) to access the Options page and increase the width again.
