### ISSUE TITLE
Investigate Media Session api

### ISSUE THREAD

**Issue by pvrs12** [pvrs12/Anesidora#74]

**Comment by pvrs12** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API

**Comment by hucario** [comment]
is this coincidence? I literally just added the media session api into genericplayer tonight

**Comment by pvrs12** [comment]
total coincidence. i saw https://github.com/snaphat/pandora_media_session when i was updating versions and figured that would be a good idea

**Comment by pvrs12** [comment]
https://github.com/pvrs12/Anesidora/pull/75
