### ISSUE TITLE
In Chrome I can't sign in if I have this activated.

### ISSUE THREAD

**Issue by DarkAlchy** [pvrs12/Anesidora#77]
If I remove the new version, or I disable it, I can log in fine but if it is active I get an invalid password/email.  Took me 20 minutes of many tries until I narrowed it down.

Some reason this addon will not let me login either at Pandora.com OR using it to log in.

**Comment by hucario** [comment]
Found what's causing this- needed to be more specific in setting User-Agent. I'll submit a PR that limits it to the JSON endpoint.

**Comment by DarkAlchy** [comment]
Fantastic.  Figured it was something minute.  Strange thing is that it was interfering with even logging into the website itself and that should not ever happen.

**Comment by pvrs12** [comment]
Uhhh, didn't think that would close it...? will wait for your confirmation

**Comment by pvrs12** [comment]
Also, if this issue persists, we can add another header to all of "our" requests which identifies them and then only modify them in https://github.com/pvrs12/Anesidora/blob/47f61a842d683c84f9e7c8e999c6aaa9aebaa36a/common/js/background.js#L10. Can also remove that header before sending onwards.

But we'll see how this works as is in v2.1.3

**Comment by DarkAlchy** [comment]
What is the reason the extension interfered with logging into the website directly?  Shouldn't the extension sit in the background and do nothing until I use it?

Where do I go to grab this version at?

**Comment by pvrs12** [comment]
Should be able to get it here https://github.com/pvrs12/Anesidora/releases/download/v2.1.3/anesidora__chrome.zip

It was modifying those requests due to some of the changes necessary to keep Anesidora working. The filter on these requests was set slightly too broadly and so was interfering with all requests to *.pandora.com

**Comment by DarkAlchy** [comment]
Fixed now for the addon/extension logging in, as well as directly on the web site.

Thanks again.

**Comment by hucario** [comment]
> What is the reason the extension interfered with logging into the website directly? Shouldn't the extension sit in the background and do nothing until I use it?

Preferably, that's what it _should_ do, but as of now there is no API to modify _a specific request_ with the permissions necessary to change the `User-Agent` header. There's only a bulk option. Like pvrs12 said, you could work around this by setting something for the filter to catch ("A-ha! This has the `X-SENTFROM-ANESIDORA` header! I must modify its `User-Agent`!") but we haven't, as it's generally unnecessary with filters. I just set it a bit too broadly.

(Fun fact! Usually this wouldn't even be an issue. It would just be an unnecessary header set. However, Pandora sees the libcurl header and says "hold up only browsers are supposed to use this endpoint >:(" and blocks it _manually_)

**Comment by DarkAlchy** [comment]
Well, I am seriously noticing something funky happening.  I started it up, and played 2 songs then put it on pause and my browser is getting slower and slower as I go.  On youtube I post a comment, and I am now 1 whole word faster than it is so I can stop typing and see my characters being ghost written.

**Comment by hucario** [comment]
I'll grant that it's suspicious that it's happening after an update, but that may not be an Anesidora problem- if you disable Anesidora does it get better?

**Comment by DarkAlchy** [comment]
Well, I shut down the browser then loaded it back up the behaviour is gone.  I have not started the addon this time.
