### ISSUE TITLE
firefox nightly android

### ISSUE THREAD

**Issue by swan77777** [pvrs12/Anesidora#82]
Trying to get this to work with Firefox Nightly app on android. I've got Anesidora in an addon collection, and it seems to be working except there's no sound, and the progress bar for a song doesn't move. The song banner graphic pulls up fine so it seems to be hitting the Pandora API fine. Not sure if there's some setting I need to change. I tried also testing on another website to test sound and it worked fine there. Note that I had this working with an old version of Firefox app (back before Firefox removed most of the addons). Thanks.

**Comment by hucario** [comment]
I don't have Android, or Firefox Nightly, or even just Firefox, so I can't help with this.
@pvrs12 You have anything?

**Comment by pvrs12** [comment]
Looks like this is the issue `Cannot play media. No decoders for requested formats: audio/aac`

I should be able to change the media format if running on android. Should be a patch released tonight/tomorrow.


Would you mind showing me how you're installing Anesidora on Firefox mobile? I've never used addon collections

**Comment by swan77777** [comment]
Sure thing.
Get the Firefox Nightly app (different than Firefox).
Go to addons.mozilla.org and create an account - details for creating collection is probably best just looked at here (but pretty straight-forward):
https://support.mozilla.org/en-US/kb/how-use-collections-addonsmozillaorg?utm_source=blog.mozilla.org&utm_medium=post&utm_content=expanded-extension-support-in-firefox-for-android-nightly
Once you've created the collection, you can search for Anesidora and it will now show up to be added.
Note that you will need the 8 digit url in the path below.
 
Next, in Firefox nightly app:
Go to settings -> About and tap on the logo 5 times to enable debug menu.
Now Custom Addon Collection will be available in settings.
Click that and then fill in the name and 8 digit code (for User ID) and collection name from above to link.
App will restart, and then Anesidora should show up in addons in Firefox Nightly.
Details for this part can be found here:
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly
 
Let me know if you have any issue - I"ll help if I can.
 
--Nate
 
 
-----Original Message-----
From: "Patrick Vares" ***@***.***
Date: 06/02/2021 07:23 PM
To: "pvrs12/Anesidora" ***@***.***>
CC: "Author" ***@***.***>
Subject: Re: [pvrs12/Anesidora] firefox nightly android (#82)


Looks like this is the issue Cannot play media. No decoders for requested formats: audio/aac
I should be able to change the media format if running on android. Should be a patch released tonight/tomorrow.
Would you mind showing me how you're installing Anesidora on Firefox mobile? I've never used addon collections—

**Comment by pvrs12** [comment]
That's awesome! I'd been missing addons on mobile, so this is a huge help. Thanks for the info about this!

I just tested the newest version with this setup too (rather than the dev setup) and it seems to be working. Hopefully the same works for you!

**Comment by swan77777** [comment]
Glad I could help - works on my end as well! Thanks for the fix! This is my favorite addon for mobile!
 
--Nate
 
-----Original Message-----
From: "Patrick Vares" ***@***.***
Date: 06/02/2021 10:16 PM
To: "pvrs12/Anesidora" ***@***.***>
CC: "swan77777" ***@***.***>, "Author" ***@***.***>
Subject: Re: [pvrs12/Anesidora] firefox nightly android (#82)


That's awesome! I'd been missing addons on mobile, so this is a huge help. Thanks for the info about this!
I just tested the newest version with this setup too (rather than the dev setup) and it seems to be working. Hopefully the same works for you!—
