### ISSUE TITLE
V2.2.2 Fails on Firefox/Windows

### ISSUE THREAD

**Issue by rfi54** [pvrs12/Anesidora#85]
V2.2.2 for Firefox (89.0 64 bit) on Windows seems to be broke.  The Anesidora Icon is blank and when I open it, the window is blank.  I tried removing and re-installing Anesidora but no change.

**Comment by hucario** [comment]
attempting to reproduce

**Comment by hucario** [comment]
yeah, that's a problem alright. works fine on chrome, but firefox is bugging out something big

**Comment by hucario** [comment]
so... for some reason this url fails:
`jar:file:///path/to/anesidora_firefox.xpi!/images/anesidora-48.png`
but this succeeds:
`jar:file:///path/to/anesidora_firefox.xpi!/images%5Canesidora-48.png`
I don't know if that's actually relevant but it appears to be the reason it looks so odd on about:extensions
@pvrs12, I have no idea what's going on. Any thoughts?

**Comment by pvrs12** [comment]
Jeeze. I definitely didn't test enough

It for sure has to do with https://github.com/pvrs12/Anesidora/commit/b6fd3174d192aa2815d129554bf49668eea2cddd

**Comment by hucario** [comment]
aaand with that I'm leaving you with the mess because you sound like you know what caused this

**Comment by pvrs12** [comment]
Oh wow, this may be one of the dumber errors... it looks like it's related to the packaging script updates that I had attempted...

**Comment by pvrs12** [comment]
So it _should_ be fixed. If you want to update immediately you can remove Anesidora and reinstall from the Mozilla addons page
https://addons.mozilla.org/en-US/firefox/addon/anesidora/

**Comment by rfi54** [comment]
Seems to work now.  Thanks guys for the quick work!

**Comment by aaron766** [comment]
I am having this issue as well. I have tried to remove the addon and reinstall, and it is still not working in the latest version of Firefox.

**Comment by pvrs12** [comment]
@rfi54 can you confirm what version you have installed?

You should be able to see it from about:addons and looking at Anesidora details

![image](https://user-images.githubusercontent.com/6956401/121114614-02e48880-c7e2-11eb-8e26-1662f50bf701.png)

**Comment by rfi54** [comment]
2.2.1_revert2.

**Comment by pvrs12** [comment]
Oh, sorry. There was another comment here that said it hadn't worked. Since you're good I'm going to close.

Thanks for the report and confirm!
