### ISSUE TITLE
Anesidora Can't Launch, even after uninstall/reinstsall of extension

### ISSUE THREAD

**Issue by JathTyki** [pvrs12/Anesidora#86]
Hello,

Anesidora automatically updated a few days ago (looks like on the 7th) and since then, even after uninstalling/reinstalling, it won't actually launch the extension anymore it looks like. It's just blank.

Here's a picture of it in my Firefox: https://imgur.com/Ann5BCi

Thank you.

**Comment by lovelydumpling** [comment]
Seems to be a continuation of #85. What version do you have installed, when you go to about:addons and check Anesidora's details? 
![image](https://user-images.githubusercontent.com/30986053/121382362-5eef0000-c8fb-11eb-83e2-a627ce4ffe73.png)

I don't work on this project but I imagine this information will be helpful to them.

**Comment by JathTyki** [comment]
![image](https://user-images.githubusercontent.com/8599699/121389236-30cce880-c91a-11eb-93e3-b999fa265ef9.png)

**Comment by pvrs12** [comment]
Thanks @lovelydumpling

@JathTyki you're running the bugged version. Can you please try to uninstall/reinstall again? I've removed thay from the store fully so it shouldn't attempt to reinstall again (hopefully)

________________________________
