### ISSUE TITLE
Anesidora Stuck On Login Page

### ISSUE THREAD

**Issue by FlapMyJax** [pvrs12/Anesidora#88]
I've recently been unable to sign into Anesidora, And I have no clue why, As of restarting my PC, to just The browser itself, Nothing, Still doesn't respond.

https://user-images.githubusercontent.com/87390741/125509793-0032bb5b-114c-4b84-a7fa-e9e2b6e23d94.mp4

**Comment by hucario** [comment]
Are you running the latest version of anesidora? If not, this could be a duplicate of #67

**Comment by FlapMyJax** [comment]
> 
> 
> Are you running the latest version of anesidora? If not, this could be a duplicate of #67

Doesn't it just automatically update?

**Comment by FlapMyJax** [comment]
> 
> 
> Are you running the latest version of anesidora? If not, this could be a duplicate of #67

As far as I know, Yes it is the latest version, And I was playing a shitload of music earlier, And then it logs me out and then, I do not have any access.

**Comment by FlapMyJax** [comment]
> 
> 
> Are you running the latest version of anesidora? If not, this could be a duplicate of #67

As of now, I think its still happening, I don't know if its like this for anyone else but,

**Comment by hucario** [comment]
I don't actually know why this is happening, but here's some things you could do to help debug:
1. Go to chrome://extensions and turn on developer mode
2. Press **`details`** on Anesidora's card
3. Press this link:
![image](https://user-images.githubusercontent.com/50851047/125645770-1ff5a06b-c056-4c0c-ae84-5dd0176a2eeb.png)
4. You should now see the chrome devtools. Open the network tab by pressing this button:
![image](https://user-images.githubusercontent.com/50851047/125645917-c3a55522-b10a-4169-bae7-5c069117cfec.png)
5. While recording your screen, attempt to log into anesidora again. Here's an example video I made showing these steps:

https://user-images.githubusercontent.com/50851047/125648936-6a684f3e-b545-4005-be50-429ae33538ca.mp4


(As a side note, I can't reproduce this issue. That doesn't mean that it's not happening, just that I couldn't figure out how to do it)

**Comment by FlapMyJax** [comment]
> 
> 
> I don't actually know why this is happening, but here's some things you could do to help debug:
> 
>     1. Go to chrome://extensions and turn on developer mode
> 
>     2. Press **`details`** on Anesidora's card
> 
>     3. Press this link:
>        ![image](https://user-images.githubusercontent.com/50851047/125645770-1ff5a06b-c056-4c0c-ae84-5dd0176a2eeb.png)
> 
>     4. You should now see the chrome devtools. Open the network tab by pressing this button:
>        ![image](https://user-images.githubusercontent.com/50851047/125645917-c3a55522-b10a-4169-bae7-5c069117cfec.png)
> 
>     5. While recording your screen, attempt to log into anesidora again. Here's an example video I made showing these steps:
> 
> 
> 2021-07-14.08-26-28.mp4
> 
> (As a side note, I can't reproduce this issue. That doesn't mean that it's not happening, just that I couldn't figure out how to do it)

I'm not a Chrome User, I still use Firefox, As of now, Could you show me another Method to do so?

**Comment by chicago77** [comment]
I am having this same issue and I am using Chrome Version 91.0.4472.124 (Official Build) (32-bit)

![Capture](https://user-images.githubusercontent.com/7304225/125841641-bcd4c219-d902-4d67-9fbe-51c65e4b2106.JPG)

**Comment by FlapMyJax** [comment]
Yeah, I got no Idea whats happening atm, Literally Was playing music, Next thing it logs me out of it, I try to relog, I can't.

**Comment by hucario** [comment]
> I'm not a Chrome User, I still use Firefox, As of now, Could you show me another Method to do so?

As @chicago77 has provided a screenshot, you don't need to anymore.
It looks very much like you guys are still using an old version of Anesidora`[0]`, so just to make sure please uninstall anesidora and then reinstall using these links:

Chrome[1]: https://github.com/pvrs12/Anesidora/releases/download/v2.2.1/anesidora__chrome.zip
Firefox[2]: https://github.com/pvrs12/Anesidora/releases/download/v2.2.1/anesidora__firefox.xpi

<details>
    <summary>Fruit by the footnotes</summary>
<pre><code>[0]: I think that because it exactly matches the requests that we saw in #67.
[1]: this stackoverflow answer should show how to do it:
<a href="https://stackoverflow.com/a/24577660/11726576">https://stackoverflow.com/a/24577660/11726576</a>
[2]: this WikiHow article, while obnoxious, should show how to do it:
<a href="https://www.wikihow.com/Install-Firefox-Extensions#Installing-Extensions-Manually-from-an-XPI-File">https://www.wikihow.com/Install-Firefox-Extensions#Installing-Extensions-Manually-from-an-XPI-File</a></code></pre>
</details>

**Comment by chicago77** [comment]
Thank you @hucario this worked wonders!

**Comment by FlapMyJax** [comment]
> 
> 
> > I'm not a Chrome User, I still use Firefox, As of now, Could you show me another Method to do so?
> 
> As @chicago77 has provided a screenshot, you don't need to anymore.
> It looks very much like you guys are still using an old version of Anesidora`[0]`, so just to make sure please uninstall anesidora and then reinstall using these links:
> 
> Chrome[1]: https://github.com/pvrs12/Anesidora/releases/download/v2.2.1/anesidora__chrome.zip
> Firefox[2]: https://github.com/pvrs12/Anesidora/releases/download/v2.2.1/anesidora__firefox.xpi
> Fruit by th
